services:
  - type: web
    name: orderops-api
    env: docker
    healthCheckPath: /health
    preDeployCommand: "python scripts/migrate.py"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: "https://orderops-admin.vercel.app"
      - key: API_KEY
        sync: false